Unable to connect to databse for some reason, the the parameter information being retrieved properly wihtout issues but when the 
lambda begins running the function to connect to the database it keeps failing.
Ensured that the Lambda function is connected to the correct VPC, Security group. 